### ISSUE TITLE
Assets offered by a dataspace participant are visible in its own catalog

### ISSUE THREAD

**Issue by cpeeyush** [agera-edc/MinimumViableDataspace#135] opened 2022-05-11 11:34 UTC
## Description

Assets offered by a dataspace participant are visible in its own catalog.

## Expected behavior

Catalog should filter out self-owned assets from catalog.

**Comment by paullatzelsperger** [comment] 2022-05-11 12:05
this sounds like the connector doesn't filter "itself" out of the node directory. Maybe this has to do with the custom refresh logic?
Check [here](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/7e8e2b1aef9ec5570dab7a14ba2ba81a345e08b8/extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogCacheExtension.java#L168) to see how the connector does it. Also, the custom refresh logic is not needed anymore, now that [#1273](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/1273) is merged.

**Comment by algattik** [comment] 2022-05-11 15:36
In https://ageramvdregistry.file.core.windows.net/registry/demo2-company3.json

```
{"name":"urn:connector:demo2-company3","supportedProtocols":["ids-multipart"],"url":"http://demo2-company3-edc-mvd.northeurope.azurecontainer.io:8282"}
```

in https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/9d236f09-93d9-4f41-88a6-20201a6a1abc/resourceGroups/rg-company3-demo2/providers/Microsoft.ContainerInstance/containerGroups/demo2-company3-edc/containers:

```
EDC_CONNECTOR_NAME | connector-company3
```

The cause seems to be that the name in the registry JSON file does not match the name in EDC_CONNECTOR_NAME.

**Closed** 2022-05-13 07:00 UTC
Labels: bug, MVD
